Repository ottohellwig/wellbeing-tracker, pull requests merged in 2024-06, with the labels that each got.

#54 added seconds to detailed report
  Wellness_Tracker.db
  src/main/java/dao/ReportDAO.java
Labels: enhancement

#56 Create README.md
  README.md
Labels: documentation

#57 Logs update
  logs.txt
Labels: documentation

#58 Update README.md
  README.md
Labels: documentation, enhancement
